spring:
  application:
    name: pagos-service

  datasource:
    url: jdbc:postgresql://localhost:5432/pagos_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: basic

clients:
  reservas:
    url: http://localhost:8085

server:
  port: 8086