spring:
  application:
    name: complejos-service

  datasource:
    url: jdbc:postgresql://localhost:5432/complejos_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8083